name: VelocityGuard CI with Maven + Spigot

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Run BuildTools
        run: mkdir buildtools && wget -O buildtools/BuildTools.jar https://hub.spigotmc.org/jenkins/job/BuildTools/lastSuccessfulBuild/artifact/target/BuildTools.jar && java -jar buildtools/BuildTools.jar --rev 1.8.8
      - name: Build with Maven
        run: mvn clean package
      - name: Copy artifacts
        run: mkdir artifacts && cp velocityguard-backend/target/velocityguard-backend.jar artifacts/velocityguard-backend.jar && cp velocityguard-proxy/target/velocityguard-proxy.jar artifacts/velocityguard-proxy.jar
      - name: Upload artifacts
        uses: actions/upload-artifact@v1.0.0
        with:
          # Artifact name
          name: VelocityGuard
          # Directory containing files to upload
          path: artifacts/
